### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by prithajnath** [prithajnath/my-secret-santa#3]
These forms need to be secured by CSRF tokens asap

- Edit profile
- Change password
- Create pairs (admin)

**Comment by AlexLanzano** [comment]
I believe this to be extremely unnecessary. Any competent internet user should always clear cookies and user sessions after they are finished. On top of that, they should AT LEAST be covered by 3 to 5 different VPNs.  Also each browser session should be isolated in a VM.
